name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6

      - name: Build
        run: go build 

      - name: Rename env
        run: mv .env.example .env

      - name: Run
        run: |
          go run . &
          echo "Server started"

      - name: Wait
        run: sleep 3

      - name: Test
        run: |
          cd tests 
          go test -v

      - name: rename env
        run: mv .env .env.example
